config/routes.rb
Rails.application.routes.draw do

  root 'polygon#map'
  delete 'delete_map' => 'polygon#destroy'
  get 'save_polygon' => 'polygon#save_polygon'
  post 'update_polygon' => 'polygon#update_polygon'

end

app/models/polygon.rb
class Polygon < ActiveRecord::Base
	serialize :polygons_list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/polygon_controller.rb
class PolygonController < ApplicationController

  before_action :check_polygon, only:[:map]
  before_action :set_map, only: [:destroy, :update_polygon]
  before_action :token_authentication, only: [:service_areas]

  def map
    @map = Polygon.all.order(:name)
    if @map.present?
      @hash = []
      @map.each do |map|
        poly = Gmaps4rails.build_markers(map.polygons_list) do |polygon, point|
          point.lat polygon[1]['lat']
          point.lng polygon[1]['lng']
        end
        @hash.push(poly)
      end
    end
  end

def check_service_area
  if params[:lat].present? && params[:lng].present?
    @maps = Polygon.all
    @result = []
    @maps.each do |map|
      @a = []
      map.polygons.each do |m|
        lat = m[1]['lat'].to_f
        lng = m[1]['lng'].to_f
        @a<< Geokit::LatLng.new(lat,lng)
      end

      polygon = Geokit::Polygon.new(@a)
      point = Geokit::LatLng.new(params[:lat],params[:lng])
      @result << polygon.contains?(point)
    end
   if @result.include?(true)
    return  render json: {message: "Service is available in this area"}, status: 200
   else
    return render json: {message: "service is currently not available in your area"}, status: 200
   end
  end
end

  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to root_path(), notice: 'Polygon deleted successfully.' }
      format.json { head :no_content }
    end
  end

  def save_polygon
    @map = Polygon.create(name: params[:name], polygons_list: params[:polygons])
  end

  def update_polygon
    @map.polygons_list = params[:polygons]
    @map.save
  end

  def service_areas
    @rate = Config.find_by_title('Cross Region Rate')
    @service_areas = Polygon.all
  end

  private
    def check_polygon
      return if params[:name].present? && params[:polygons].present?
    end

    def set_map
      @map = Polygon.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MapDrawer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="//maps.google.com/maps/api/js?key=AIzaSyBRXZRZ2D2sB0lqQhBDsm619tV471Y5zFw"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/lodash.js/0.10.0/lodash.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= favicon_link_tag 'favicon.png' %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/polygon/_index.html.erb
<table id="datatable" class="table table-striped table-bordered" style="margin: 0px;">
  <thead>
    <tr class="colors">
      <th colspan=2>Polygons</th>
    </tr>
  </thead>
</table>
<div class="scroll" style="height: 503px;overflow-y: scroll;">
  <table id="datatable" class="table table-striped table-bordered">
    <tbody class='map_list'>
      <% @map.each_with_index do |map, index| %>
        <%= render 'map_entry', map: map, index: index %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/polygon/_map_entry.html.erb
<tr>
  <td style="height: 44px; border-right: none; text-align: left;">
    <%= map.name.try(:titleize) %>
  </td>
  <td style="width: 70px; border-left: none;">
  	<% center = map.polygons_list.count/2 %>
    <button id="draw_btn" class="btn btn-primary" style="font-size: 14px;padding: 1px 4px; float: right; margin: 0px 0px 3px 3px;" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Edit Polygon" onclick='edit_polygons(<%= map.id %>,<%= index %>,<%= map.polygons_list[center.to_s]["lat"] %>,<%= map.polygons_list[center.to_s]["lng"] %>)'><i class="fa fa-pencil"></i></button>
    <%= link_to(delete_map_path(id: map.id), method: :delete, data: { confirm: "Are you sure you want to delete this polygon?" })do %>
      <i class="btn btn-sm btn-danger fa fa-trash-o text-danger" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Delete Polygon" style="font-size: 16px;padding: 3px; float: right; margin: 0px;"></i>
    <% end %>
  </td>
</tr>

app/views/polygon/map.html.erb
<h1 style="text-align: center;">Draw, Edit or Delete Polygon on Map</h1>
<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="col-xs-10 form-group" style="padding: 0px 4px 0px 0px; height: 100%;">
    <div id="map" style='width: 100%; height: 540px;'></div>
  </div>
  <div class="col-xs-2 form-group" style="padding: 0px;">
    <button id="draw_btn" class="btn btn-info" style="float: right;" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Create Polygon" onclick='save_polygons()'><i id="draw_icon" class="fa fa-pencil"></i></button>

    <button id="save_btn" class="btn btn-success" style="float: right; display: none;" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Update Polygon" onclick='update_polygons()'><i class="fa fa-save (alias)"></i></button>

    <button id="cancel_btn" class="btn btn-warning" style="float: right; display: none;" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Cancel" onclick='cancel_update()'><i class="fa fa-times"></i></button>
    <%= render "index" %>
  </div>
</div>

<div id="polygon_name" class="modal fade" role="dialog">
  <div class="modal-dialog" style="padding-top: 120px;">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header colors">
        <button type="button" class="close colors" data-dismiss="modal" method="reset">X</button>
        <h4 class="modal-title">Polygon</h4>
      </div>
      <div class="modal-body">
        <%= text_field_tag 'name', '', autofocus: true, required: true, placeholder: "Name...", id: "name_field", class: "form-control"%>
        <br>
        <button type="button" class="btn btn-info" style="float; right;" data-dismiss="modal" onclick='send_polygons()'>Done</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
var infoWindow = new google.maps.InfoWindow;
handler = Gmaps.build('Google');
$(function() {
  make_map(null);
});
function make_map(id){
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      <% if @hash.present? %>
        <% @hash.each.with_index do |gon, index|%>
          if (<%= index %> == id)
          {
            edit_polygon = handler.addPolygon(<%=raw gon.to_json %>,{
             strokeColor: '#FF0000',
             editable: true,
             //fillColor: '#FF0000'
            });
          }
          else
          {
            poly = handler.addPolygon(<%=raw gon.to_json %>,{
               strokeColor: '#FFBF00',
               editable: false,
               //fillColor: '#FF0000'
            });
            google.maps.event.addListener(poly.getServiceObject(), "click", function(event) {
              infoWindow.setContent((<%= raw @map[index].name.to_json %>).toString());
              infoWindow.setPosition(event.latLng);
              infoWindow.open(handler.getMap());
            });
          }
        <% end %>
      <% end %>
      polygon_marker();
   });
}
</script>

app/views/polygon/save_polygon.js.erb
$(".map_list").append("<%= escape_javascript("#{render :partial => 'map_entry', :locals => { :map => @map }}").html_safe %>");